name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '1.17.6'

    - name: Install go1.18beta
      run: |
        go install golang.org/dl/go1.18beta1@latest
        go1.18beta1 download

    - name: Build
      run: go1.18beta1 build .

    - name: Build
      run: go1.18beta1 test .

    - name: Test With Coverage
      run: go1.18beta1 test . -coverprofile coverage.txt -covermode atomic -tags fail || true # mask process failure -- running intentional failing tests

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        verbose: true
